<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description>Today</description>
   <name>Today</name>
   <tag></tag>
   <elementGuidId>dafbabec-84e7-4c0e-bf8b-c56bbd64c49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;dropdown-item-2&quot;]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
